name: Add feed

on:
  workflow_dispatch:
    inputs:
      url:
        description: "Feed URL"
        required: true

permissions:
  contents: write

jobs:
  add-feed:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download rdigest
        run: |
          REPO_OWNER="chandru89new" # Replace with actual owner
          REPO_NAME="rdigest"   # Replace with actual repo name

          # Fetch the latest release tag
          LATEST_TAG=$(curl -s https://api.github.com/repos/$REPO_OWNER/$REPO_NAME/releases/latest | jq -r .tag_name)

          # Construct the download URL
          BINARY_URL="https://github.com/$REPO_OWNER/$REPO_NAME/releases/download/$LATEST_TAG/rdigest_linux_amd64_$LATEST_TAG.tar.gz"

          # Download and make the binary executable
          curl -L $BINARY_URL --output rdigest.tar.gz
          tar -xzf rdigest.tar.gz
          chmod +x ./rdigest

      - name: Add feed
        run: |
          export RDIGEST_FOLDER=.
          ./rdigest add ${{ inputs.url }}

      - name: Refresh feeds
        run: |
          export RDIGEST_FOLDER=.
          ./rdigest refresh

      - name: Remove binary
        run: |
          rm rdigest
          rm *.tar.gz

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit and Push Changes
        run: |
          git add .
          git commit -m "Added feed and refreshed."
          git push origin main
